# Generated by Django 3.2.8 on 2022-06-22 14:38

from django.db import migrations, models
import pan.utils


class Migration(migrations.Migration):

    dependencies = [
        ('pan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='default/user.svg', upload_to=pan.utils.get_unique_filename, verbose_name='头像'),
        ),
    ]
